---
# Source: cert-manager-webhook-vultr/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-vultr
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
---
# Source: cert-manager-webhook-vultr/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-vultr:domain-solver
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
rules:
  - apiGroups:
      - acme.vultr.com
    resources:
      - '*'
    verbs:
      - 'create'
---
# Source: cert-manager-webhook-vultr/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-vultr:flowcontrol-solver
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
rules:
  - apiGroups:
      - "flowcontrol.apiserver.k8s.io"
    resources:
      - 'prioritylevelconfigurations'
      - 'flowschemas'
    verbs:
      - 'list'
      - 'watch'
---
# Source: cert-manager-webhook-vultr/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-vultr:auth-delegator
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-vultr
    namespace: cert-manager
---
# Source: cert-manager-webhook-vultr/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-vultr:domain-solver
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-vultr:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: cert-manager-webhook-vultr/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-vultr:flowcontrol-solver
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-vultr:flowcontrol-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-vultr
    namespace: "cert-manager"
---
# Source: cert-manager-webhook-vultr/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-vultr:secret-reader
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [vultr-credentials]
    verbs: ["get", "watch"]
---
# Source: cert-manager-webhook-vultr/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-vultr:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-vultr
    namespace: cert-manager
---
# Source: cert-manager-webhook-vultr/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-vultr:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-vultr:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-vultr
---
# Source: cert-manager-webhook-vultr/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-vultr
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: cert-manager-webhook-vultr
    release: cert-manager-webhook-vultr
---
# Source: cert-manager-webhook-vultr/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-vultr
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app: cert-manager-webhook-vultr
      release: cert-manager-webhook-vultr
  template:
    metadata:
      labels:
        app: cert-manager-webhook-vultr
        release: cert-manager-webhook-vultr
    spec:
      serviceAccountName: cert-manager-webhook-vultr
      containers:
        - name: cert-manager-webhook-vultr
          image: "vultr/cert-manager-webhook-vultr:v0.3.1"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "acme.vultr.com"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-vultr-webhook-tls
---
# Source: cert-manager-webhook-vultr/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.vultr.com
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-vultr-webhook-tls"
spec:
  group: acme.vultr.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-vultr
    namespace: cert-manager
  version: v1alpha1
---
# Source: cert-manager-webhook-vultr/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-vultr-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
spec:
  secretName: cert-manager-webhook-vultr-ca
  duration: 43800h # 5y
  issuerRef:
    name: cert-manager-webhook-vultr-selfsign
  commonName: "ca.cert-manager-webhook-vultr.cert-manager"
  isCA: true
---
# Source: cert-manager-webhook-vultr/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-vultr-webhook-tls
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
spec:
  secretName: cert-manager-webhook-vultr-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: cert-manager-webhook-vultr-ca
  dnsNames:
  - cert-manager-webhook-vultr
  - cert-manager-webhook-vultr.cert-manager
  - cert-manager-webhook-vultr.cert-manager.svc
---
# Source: cert-manager-webhook-vultr/templates/issuers.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vultr-letsencrypt-staging
spec:
  acme:
    email: changeme@email.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: vultr-letsencrypt-staging
    solvers:
      - dns01:
          webhook:
            groupName: acme.vultr.com
            solverName: vultr
            config:
              apiKeySecretRef:
                key: apiKey
                name: vultr-credentials
---
# Source: cert-manager-webhook-vultr/templates/issuers.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vultr-letsencrypt-prod
spec:
  acme:
    email: changeme@email.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: vultr-letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            groupName: acme.vultr.com
            solverName: vultr
            config:
              apiKeySecretRef:
                key: apiKey
                name: vultr-credentials
---
# Source: cert-manager-webhook-vultr/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-vultr-selfsign
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: cert-manager-webhook-vultr/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-vultr-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-vultr
    chart: cert-manager-webhook-vultr-0.4.1
    release: cert-manager-webhook-vultr
    heritage: Helm
spec:
  ca:
    secretName: cert-manager-webhook-vultr-ca
